
FROM registry.cn-shenzhen.aliyuncs.com/kstudio/utils-nodexm:latest

MAINTAINER Kinfen


RUN apk add --no-cache --virtual .build-deps \
        gcc \
        gnupg \
        libgcc \
        make \
        python2 \
        libstdc++

CMD ["node"]



