sudo: required
language: node_js
services:
  - docker
before_install:
- docker -v

script:
- docker login -u $YUN_USERNAME -p $YUN_PASSWORD registry.cn-shenzhen.aliyuncs.com
- sh build-yun.sh


after_success:
- sh push-yun.sh 
- docker login -u $USER_USERNAME -p $USER_PASSWORD
- sh push.sh 
  
