sudo: required
language: node_js
services:
  - docker
before_install:
- docker -v

script:
- sh build-yun.sh


after_success:
- docker login -u $YUN_USERNAME -p $YUN_PASSWORD registry.cn-shenzhen.aliyuncs.com
- sh push-yun.sh 
  
