sudo: required
language: node_js
services:
  - docker
before_install:
- docker -v
- UTILS1="utils-lite"

script:
- docker build ./${UTILS1} -t kinfen/${UTILS1}:latest

after_success:
  - docker login -u $DOCKER-USERNAME -p $DOCKER-PASSWORD
  - docker push kinfen/${UTILS1}:latest

  
  
