sudo: required
language: node_js
services:
  - docker
before_install:
- docker -v
- UTILS="utils-lite utils-nodexm"

script:
- for util in $UTILS; do
  docker build ./$util -t kinfen/$util:latest
  done


after_success:
- docker login -u $DOCKER-USERNAME -p $DOCKER-PASSWORD
- for util in $UTILS; do
  docker push kinfen/$util:latest
  done  
  
