sudo: required
language: node_js
services:
  - docker
before_install:
- docker -v

script:
- docker build ./utils-lite -t kinfen/utils-lite:latest

after_success:
  - docker login -u kinfen -p deadkill
  - docker push kinfen/utils-lite:latest

  
  
