sudo: required
language: node_js
services:
  - docker
before_install:
- docker -v

env:
- UTILS=kadm-mongo

script:
- docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD
- sh build.sh


after_success:
- sh push.sh 
- docker login --username=$YUN_USERNAME --password=$YUN_PASSWORD registry.cn-shenzhen.aliyuncs.com
- sh push-yun.sh 

  
