sudo: required
language: node_js
services:
  - docker
before_install:
- docker -v
- UTILS="utils-lite utils-nodexm"

script:
- sh build.sh


after_success:
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- sh push.sh 
  
