version: "3"
services:
  server:
    image:  kinfen/utils-ss
    ports:
      - "5234-5236:5234-5236"
    networks:
      - webnet
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
networks:
  webnet:
