
FROM jenkins/jenkins:2.76-alpine

# Set one or more individual labels
LABEL version="0.0.1-beta"
LABEL description="for jenkins"
LABEL publishdate="2018-9-3"

# USER root
# ARG dockerGid=999
# RUN echo "jenkins ALL=NOPASSWD: ALL" >> /etc/sudoers \
# 	%% echo "docker:x:${dockerGid}:jenkins" >> /etc/group
# USER jenkins

