#!/bin/sh
echo "准备创建镜像"
docker -H $PLUGIN_DOCKERHOST login $PLUGIN_REPO -u $PLUGIN_USERNAME -p $PLUGIN_PASSWORD
docker -H $PLUGIN_DOCKERHOST build --rm $PLUGIN_CONTEXT -t $PLUGIN_REGISTRY:${PLUGIN_TAG}
docker -H $PLUGIN_DOCKERHOST push $PLUGIN_REGISTRY:${PLUGIN_TAG}
docker -H $PLUGIN_DOCKERHOST system prune -f